import Foundation

enum meadowMuseProfileText {
    static let picked = "Picked"
    static let mine = "Mine"
    static let got = "Got"
    static let empty = "Empty now, but ready for your eye makeup inspiration!"
    static let saveSuccess = "Save successfully"
    static let likeTitle = "Like Eyelook AI?"
    static let rateHint = "Rate and share your thoughts!"
    static let feedback = "Feedback"
    static let dearUser = "Dear user,"
    static let feedbackIntro = "Thank you for using Eyelook AI. Your opinion matters to us! Please take a moment to rate our application on a scale of 1 - 5 stars."
    static let feedbackScale = "\n1 star: Didn't meet my expectations.\n2 stars: Needs improvement.\n3 stars: It's okay.\n4 stars: Good, but there's room for more.\n5 stars: Amazing! I love it!\n"
    static let feedbackOutro = "\nAlso, feel free to leave your comments below. Your feedback will help us make PatternPaint AI even better.Thank you!"
    static let inter = "Inter"
    static let suggestion = "Suggestion"
    static let pleaseEnter = "Please Enter"
    static let history = "History"
    static let keywords = "Keywords："
    static let saveToLocal = "Save to local"
    static let eyelookAI = "Eyelook AI"
    static let prompt = "Please enter the keywords that inspire your eye make-up"
    static let counter = "200"
    static let permissionGranted = "Permission granted"
    static let permissionDenied = "Permission denied"
    static let noGalleryPermission = "No permission to access gallery"
    static let downloading = "Downloading..."
    static let downloadSuccess = "Download successfully"
    static let saveFailed = "Save failed"
    static let saveError = "Error occurred while saving"
    static let noImages = "No images available"
    static let youHave = "You have"
    static let moreChances = "more chances to open the box"
    static let thereAre = "There are"
    static let surprises = "surprises"
    static let giftBox = "in the gift box"
}
