import Foundation

enum petalTrailCompleteText {
    static let walletBalance = "Wallet Balance"
    static let rechargeAmount = "Recharge amount"
    static let diamond = "Diamond"
    static let payPrefix = "Are you sure you want to pay "
    static let paySuffix = "Diamond?"
    static let insufficient = "Sorry, your balance is insufficient"
    static let purchaseDone = "purchase completed"
    static let purchaseFailed = "Failed purchase"
    static let productLoading = "The product data is still loading"
    static let purchaseCancelled = "Payment has been cancelled"
    static let purchasePending = "Payment is pending"
    static let productUnavailable = "This item is unavailable"
    static let preparingPurchase = "Preparing purchase..."

    static let settings = "Settings"
    static let privacyPolicy = "Privacy Policy"
    static let userAgreement = "User Agreement"
    static let blocklist = "Blocklist"
    static let aboutUs = "About Us"
    static let deleteAccount = "Delete account"
    static let logOut = "Log out"
    static let continueAction = "Continue"
    static let deleteWarning = "Deleting the account will clear the account data. Are you sure to delete?"
    static let logoutWarning = "Are you sure you want to log out?"

    static let avatar = "Avatar"
    static let nickname = "Nickname"
    static let defaultNickname = "Zaylee"
    static let enterNickname = "Please enter your nickname"
    static let nameChanged = "The user name is successfully changed"
    static let profileChanged = "The profile is successfully changed"
    static let nameEmpty = "The user name cannot be empty"

    static let following = "Following"
    static let fans = "Fans"
    static let modifyProfile = "Modify Profile"
    static let revocate = "Revocate"
    static let version = "Version 1.0.0"

    static let requestCameraTitle = "Request Access to Camera and Microphone"
    static let requestCameraBody = "To provide the best user experience, our application requires access to your camera and microphone. These permissions will be used for the following purposes:\n\nCamera: To take photos and record videos so you can share special moments with friends.\n\nMicrophone: To record sound and audio for voice and video calls.\n\nWe assure you that we do not collect or share your personal information, and all access will be limited to the needs of the app's functionality. You can manage these permissions in your privacy settings at any time."
    static let requestPhotosTitle = "Request Access to Photos"
    static let requestPhotosBody = "In order for the application to save and manage your photos securely and privately on your device, please allow access to your photos.\n\nWe assure you that we do not collect or share your personal information, and all access will be limited to the needs of the app's functionality. You can manage these permissions in your privacy settings at any time."
    static let allowAccess = "Allow Access"
    static let notNow = "Not Now"

    static let sharePrompt = "Your eye makeup inspiration could be the spark someone else needs. Upload your pictures and start a trend!"
    static let shareNeedsImage = "Please upload an image first"
    static let shareSuccess = "Share success"
    static let releaseSuccess = "Posted successfully. It will be shown after review."
    static let ok = "OK"

    static let reportPlaceholder = "Enter your reason here..."
    static let reportDone = "The user reports successfully"
    static let submitReport = "Submit Report"
    static let blockDone = "User masking succeeded"
    static let block = "Block"
    static let report = "Report"
    static let cancel = "Cancel"

    static let chat = "Chat"
    static let onCall = "On a call..."
    static let noCamera = "No cameras available"
    static let noAnswer = "There is no answer at the moment, please try again later"
    static let nancy = "Nancy"
    static let baldwin = "Baldwin"
    static let rune = "Rune"
    static let maxLee = "Max Lee"
}
